# Generated by Django 4.1.7 on 2023-02-24 22:32

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=234)),
                ('lastname', models.CharField(max_length=234)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email_address', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('ADMIN', 'Administration'), ('IT', 'Information Technology'), ('MEDIA', 'Media')], max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=100)),
                ('state_of_origin', models.CharField(max_length=234)),
                ('account_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Enter a valid account number')])),
                ('bank', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=234)),
            ],
        ),
    ]
