# Generated by Django 4.1.7 on 2023-02-27 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='specialization',
            field=models.CharField(default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.staff'),
        ),
        migrations.AlterField(
            model_name='it',
            name='specialization',
            field=models.CharField(default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='it',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.staff'),
        ),
        migrations.AlterField(
            model_name='media',
            name='specialization',
            field=models.CharField(default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.staff'),
        ),
    ]
