# Generated by Django 4.1.7 on 2023-02-27 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_admin_specialization_alter_admin_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Admin'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media'},
        ),
        migrations.AddField(
            model_name='staff',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_admin', to='member.admin'),
        ),
        migrations.AddField(
            model_name='staff',
            name='it',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_it', to='member.it'),
        ),
        migrations.AddField(
            model_name='staff',
            name='media',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_media', to='member.media'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_member', serialize=False, to='member.staff'),
        ),
        migrations.AlterField(
            model_name='it',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='it_member', serialize=False, to='member.staff'),
        ),
        migrations.AlterField(
            model_name='media',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='media_member', serialize=False, to='member.staff'),
        ),
    ]
