# Generated by Django 4.1.7 on 2023-03-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_previlages_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previlages',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previlages_member', to='member.admin'),
        ),
    ]
