# Generated by Django 4.1.7 on 2023-03-01 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_admin_is_admin_delete_previlages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='it',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='media',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='it',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='media',
        ),
        migrations.AddField(
            model_name='admin',
            name='staff_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='it',
            name='staff_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='staff_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member.staff'),
            preserve_default=False,
        ),
    ]
