# Generated by Django 4.1.7 on 2023-03-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='role',
        ),
        migrations.RemoveField(
            model_name='it',
            name='staff_ptr',
        ),
        migrations.AddField(
            model_name='it',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
