# Generated by Django 4.1.7 on 2023-03-01 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_delete_role_remove_it_staff_ptr_it_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='it',
            name='staff',
            field=models.ForeignKey(default='it_staff', on_delete=django.db.models.deletion.CASCADE, to='member.staff'),
        ),
    ]
