# Generated by Django 4.1.7 on 2023-03-01 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_it_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='it',
            name='id',
        ),
        migrations.RemoveField(
            model_name='it',
            name='staff',
        ),
        migrations.AddField(
            model_name='it',
            name='staff_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member.staff'),
            preserve_default=False,
        ),
    ]
