# Generated by Django 4.1.7 on 2023-03-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_remove_it_id_remove_it_staff_it_staff_ptr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='staff_ptr',
        ),
        migrations.RemoveField(
            model_name='it',
            name='staff_ptr',
        ),
        migrations.RemoveField(
            model_name='media',
            name='staff_ptr',
        ),
        migrations.AddField(
            model_name='admin',
            name='staff',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_member', serialize=False, to='member.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='it',
            name='staff',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='it_member', serialize=False, to='member.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='staff',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='media_member', serialize=False, to='member.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_admin', to='member.admin'),
        ),
        migrations.AddField(
            model_name='staff',
            name='it',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_it', to='member.it'),
        ),
        migrations.AddField(
            model_name='staff',
            name='media',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_media', to='member.media'),
        ),
    ]
