# Generated by Django 4.1.7 on 2023-03-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_remove_admin_staff_ptr_remove_it_staff_ptr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Admins'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='it',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='media',
        ),
    ]
